server:
    port: 8080 # API Gateway will run on port 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false # Disable discovery locator
              # 글로벌 CORS 설정
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true



# logging configuration
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    com.example.gw: INFO
# endpoint config for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
